### ISSUE TITLE
Using split for param may lose part of the value

### ISSUE THREAD

**Issue by elidoran** [WorkPlusFE/workplus-query-string#2]
If a param's value contains more than one equal sign (which isn't encoded to hide it) then your library will cut off the extra parts.

 See [here](https://github.com/WorkPlusFE/workplus-query-string/blob/master/index.js#L18-L20). The parts in the array from index 2 and on will be lost.

Possible solution:

```javascript
const index = param.indexOf('=')
if (index < 0) {
  set[param] = null
} else {
  set[param.slice(0, index)] = param.slice(index + 1)
}
```

**Comment by Alex-fun** [comment]
@elidoran Thank you for your reminder!

The code is not rigorous enough, I will fix it.
